version: '3'

# Define the services/containers to be run
services:
 database:
  container_name: mongo
  image: mongo
  ports:
   - "27017:27017"
 dbseed:
  build: dbseed
  depends_on:
    - database
 angular:
  container_name: frontend
  build: frontend
  ports:
   - "4200:4200"
  command: > 
        bash -c "ng serve --host 0.0.0.0 --port 4200"
 express:
  container_name: backend
  build: backend
  ports:
   - "3000:3000"
